### ISSUE TITLE
unable to create the dev cluster

### ISSUE THREAD

**Issue by nandhigb** [kcdchennai/cloudnative-k8s-workshop#2]
Hi Team ,

I followed the KCD Chennai - workshop 

While trying to create a cluster - as per the below instruction - am facing error. 
https://kcdchennai.github.io/cloudnative-k8s-workshop/030_create_cluster/32_create_cluster.html

Need help to troubleshoot.
![image](https://user-images.githubusercontent.com/67903935/171981204-7b709f4c-e469-4dc9-84d0-72b91850d067.png)

**Comment by karthick-kk** [comment]
@nandhigb make sure the docker daemon is running before running a k3d command. without a container runtime k3d will not be functional.
1. you can check if docker is running or not by `docker ps`
2. if dockerd isn't started, start dockerd by issuing `sudo dockerd &`

**Comment by nandhigb** [comment]
Thank you - Post starting the docker d - it worked.
![image](https://user-images.githubusercontent.com/67903935/171983101-695f4413-d82a-49c8-a387-36b8d876491e.png)

**Comment by nandhigb** [comment]
I am encountering one more permission issues. while Exploring the cluster resources

![image](https://user-images.githubusercontent.com/67903935/171983437-bd231415-497d-4681-a2e6-103d4ff3c590.png)

Should we give any permissions to kubectl ?

![image](https://user-images.githubusercontent.com/67903935/171983475-5c423b24-c3ac-45d8-9e62-39ea8e37a518.png)

**Comment by karthick-kk** [comment]
updated the document to include basic validation before cluster creation.
