### ISSUE TITLE
 unable to Connect to Kubectl Cluster

### ISSUE THREAD

**Issue by nandhigb** [kcdchennai/cloudnative-k8s-workshop#3]
Hello Team ,

I have created the kubernetes cluster .

While following up the instructions under - Basic Kubectl Commands  - on trying out to  Connect to Kubectl Cluster.
Am getting the below error - No Nodes found.

Kindly advice.

![image](https://user-images.githubusercontent.com/67903935/171987353-ae959cfc-2ecb-4793-9bc3-36177964e7aa.png)

**Comment by karthick-kk** [comment]
What's the output of `k3d cluster list` ?

**Comment by nandhigb** [comment]
Output:
![image](https://user-images.githubusercontent.com/67903935/171988981-3c296f3f-06a6-4f57-9f6a-b5798a070ca1.png)

**Comment by karthick-kk** [comment]
> Output: ![image](https://user-images.githubusercontent.com/67903935/171988981-3c296f3f-06a6-4f57-9f6a-b5798a070ca1.png)

as per the output there is no cluster created with the name **local-cluster**, so it is obvious the error is true. Do create the cluster before trying to export its configuration to a file.

**Comment by nandhigb** [comment]
Can i modify the DevCluster creation command and create a local cluster?

k3d cluster create local-cluster --agents 3 --k3s-arg "--disable=traefik@server:0" --k3s-arg "--disable=servicelb@server:0" --no-lb --wait --registry-create devregistry:30500

**Comment by karthick-kk** [comment]
change the registry name from devregistry to localregistry or you can completely exclude the registry creation with `k3d cluster create local-cluster --agents 3 --k3s-arg "--disable=traefik@server:0" --k3s-arg "--disable=servicelb@server:0" --no-lb --wait `
